version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/app
    ports:
      - 8081:8000
    depends_on:
      - main_db

  main_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./storage/dbdata:/var/lib/mysql
    ports:
    - 33061:3306
